// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de":     &dictionary{index: deIndex, data: deData},
		"en":     &dictionary{index: enIndex, data: enData},
		"en_US":  &dictionary{index: en_USIndex, data: en_USData},
		"es":     &dictionary{index: esIndex, data: esData},
		"es_419": &dictionary{index: es_419Index, data: es_419Data},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"A simple reservation system": 2,
	"About ":                      3,
	"ReserVe.me":                  1,
	"ServerCore is a hypermedia application written with go, templ, sqlite and htmx": 4,
	"Welcome to ": 0,
}

var deIndex = []uint32{ // 6 elements
	0x00000000, 0x00000014, 0x0000001f, 0x00000041,
	0x00000041, 0x00000041,
} // Size: 48 bytes

const deData string = "" + // Size: 65 bytes
	"\x04\x00\x01 \x0f\x02Willkommen bei\x02ReserVe.me\x02Ein einfaches Reser" +
	"vierungssystem"

var enIndex = []uint32{ // 6 elements
	0x00000000, 0x00000010, 0x0000001b, 0x00000037,
	0x00000042, 0x00000091,
} // Size: 48 bytes

const enData string = "" + // Size: 145 bytes
	"\x04\x00\x01 \x0b\x02Welcome to\x02ReserVe.me\x02A simple reservation sy" +
	"stem\x04\x00\x01 \x06\x02About\x02ServerCore is a hypermedia application" +
	" written with go, templ, sqlite and htmx"

var en_USIndex = []uint32{ // 6 elements
	0x00000000, 0x00000010, 0x0000001b, 0x00000037,
	0x00000037, 0x00000037,
} // Size: 48 bytes

const en_USData string = "" + // Size: 55 bytes
	"\x04\x00\x01 \x0b\x02Welcome to\x02ReserVe.me\x02A simple reservation sy" +
	"stem"

var esIndex = []uint32{ // 6 elements
	0x00000000, 0x00000012, 0x0000001d, 0x0000003b,
	0x0000003b, 0x0000003b,
} // Size: 48 bytes

const esData string = "" + // Size: 59 bytes
	"\x04\x00\x01 \x0d\x02Bienvenido a\x02ReserVe.me\x02Un sistema de reserva" +
	"s simple"

var es_419Index = []uint32{ // 6 elements
	0x00000000, 0x00000012, 0x0000001d, 0x0000003b,
	0x0000003b, 0x0000003b,
} // Size: 48 bytes

const es_419Data string = "" + // Size: 59 bytes
	"\x04\x00\x01 \x0d\x02Bienvenido a\x02ReserVe.me\x02Un sistema de reserva" +
	"s simple"

	// Total table size 623 bytes (0KiB); checksum: 9774F1C1
